#pragma once
#include <algorithm>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <regex>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
namespace fs = std::filesystem;
inline std::string trim(std::string s) { auto b=s.find_first_not_of(" \t\r\n"); if(b==std::string::npos)return ""; return s.substr(b,s.find_last_not_of(" \t\r\n")-b+1); }
inline std::string lower(std::string s) {for(auto &c:s)if(c>='A'&&c<='Z')c=char(c+32);return s;}
inline std::string jq(const std::string& s) {std::string o="\""; const char* h="0123456789abcdef"; for(unsigned char c:s){switch(c){case '"':o+="\\\"";break;case '\\':o+="\\\\";break;case '\n':o+="\\n";break;case '\r':o+="\\r";break;case '\t':o+="\\t";break;default:if(c<32){o+="\\u00";o+=h[c>>4];o+=h[c&15];}else o+=char(c);}}return o+'"';}
inline void check_utf8(const std::string& s) {for(size_t i=0;i<s.size();){unsigned char c=s[i];if(c<128){if(c==0)throw std::runtime_error("NUL bytes are not accepted in text input");++i;continue;}int n=0;unsigned v=0;if(c>=0xC2&&c<=0xDF){n=2;v=c&31;}else if(c>=0xE0&&c<=0xEF){n=3;v=c&15;}else if(c>=0xF0&&c<=0xF4){n=4;v=c&7;}else throw std::runtime_error("Input is not valid UTF-8");if(i+n>s.size())throw std::runtime_error("Truncated UTF-8 sequence");for(int j=1;j<n;++j){unsigned char x=s[i+j];if((x&0xC0)!=0x80)throw std::runtime_error("Input is not valid UTF-8");v=(v<<6)|(x&63);}if((n==3&&v<0x800)||(n==4&&v<0x10000)||(v>=0xD800&&v<=0xDFFF)||v>0x10FFFF)throw std::runtime_error("Input contains an invalid Unicode code point");i+=n;}}
inline std::string read_text(const fs::path& p) {std::error_code size_error;auto size=fs::file_size(p,size_error);if(!size_error&&size>10*1024*1024)throw std::runtime_error("Input exceeds the 10 MiB limit");std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("Cannot open input file");std::string s((std::istreambuf_iterator<char>(f)),{});if(s.size()>10*1024*1024)throw std::runtime_error("Input exceeds the 10 MiB limit");check_utf8(s);if(s.size()>=3&&s.substr(0,3)=="\xEF\xBB\xBF")s.erase(0,3);return s;}
struct Diagnostic {size_t line;std::string field,message;};
struct Report {size_t read=0,written=0;std::vector<std::string> fields,warnings;std::vector<Diagnostic> errors;void error(size_t line,const std::string& field,const std::string& msg){if(errors.size()<100)errors.push_back({line,field,msg});}void print() const {std::cout<<"{\"ok\":"<<(errors.empty()?"true":"false")<<",\"recordsRead\":"<<read<<",\"recordsWritten\":"<<written<<",\"fieldCount\":"<<fields.size()<<",\"fields\":[";for(size_t i=0;i<fields.size();++i){if(i)std::cout<<',';std::cout<<jq(fields[i]);}std::cout<<"],\"warnings\":[";for(size_t i=0;i<warnings.size();++i){if(i)std::cout<<',';std::cout<<jq(warnings[i]);}std::cout<<"],\"errors\":[";for(size_t i=0;i<errors.size();++i){if(i)std::cout<<',';auto&e=errors[i];std::cout<<"{\"line\":"<<e.line<<",\"field\":"<<jq(e.field)<<",\"message\":"<<jq(e.message)<<'}';}std::cout<<"]}\n";}};
struct Mapping {std::string source,target,type;bool required;};
inline std::vector<Mapping> read_map(const fs::path& path) {std::vector<Mapping> result;std::unordered_set<std::string> targets;std::istringstream in(read_text(path));std::string line;size_t n=0;while(std::getline(in,line)){++n;if(trim(line).empty())continue;if(!line.empty()&&line.back()=='\r')line.pop_back();std::vector<std::string> parts;size_t begin=0;for(size_t i=0;i<=line.size();++i)if(i==line.size()||line[i]=='\t'){parts.push_back(line.substr(begin,i-begin));begin=i+1;}if(parts.size()!=4)throw std::runtime_error("Mapping line "+std::to_string(n)+" needs four tab-separated values: source, target, type, required");for(auto&v:parts)v=trim(v);if(parts[0].empty()||parts[1].empty())throw std::runtime_error("Mapping source and target must not be empty");if(parts[2]!="string"&&parts[2]!="integer"&&parts[2]!="number"&&parts[2]!="boolean")throw std::runtime_error("Unknown mapping type: "+parts[2]);if(parts[3]!="true"&&parts[3]!="false")throw std::runtime_error("Required must be true or false");if(!targets.insert(parts[1]).second)throw std::runtime_error("Duplicate JSON target: "+parts[1]);result.push_back({parts[0],parts[1],parts[2],parts[3]=="true"});}if(result.empty())throw std::runtime_error("Mapping file has no fields");return result;}
inline std::string typed(const std::string& raw,const Mapping&m,size_t line,Report&r) {auto s=trim(raw);if(s.empty()){if(m.required)r.error(line,m.source,"A required value is empty");return "null";}if(m.type=="string")return jq(raw);if(m.type=="boolean"){auto x=lower(s);if(x=="true"||x=="yes"||x=="on"||x=="1")return "true";if(x=="false"||x=="no"||x=="off"||x=="0")return "false";r.error(line,m.source,"Expected a boolean: true/false, yes/no, on/off, or 1/0");return "null";}if(m.type=="integer"){static const std::regex re("[+-]?[0-9]+");try{if(!std::regex_match(s,re))throw std::runtime_error("bad");size_t used=0;auto v=std::stoll(s,&used);if(used!=s.size())throw std::runtime_error("bad");return std::to_string(v);}catch(...){r.error(line,m.source,"Expected a signed 64-bit integer");return "null";}}static const std::regex re("-?(0|[1-9][0-9]*)(\\.[0-9]+)?([eE][+-]?[0-9]+)?");try{if(!std::regex_match(s,re))throw std::runtime_error("bad");auto v=std::stod(s);if(!std::isfinite(v))throw std::runtime_error("bad");return s;}catch(...){r.error(line,m.source,"Expected a finite JSON number");return "null";}}
inline void atomic_write(const fs::path& input,const fs::path& output,const std::string& text){if(fs::weakly_canonical(input)==fs::weakly_canonical(output))throw std::runtime_error("Output must differ from input; original files are preserved");if(fs::exists(output))throw std::runtime_error("Output already exists; choose a new filename");auto parent=output.parent_path();if(parent.empty())parent=".";if(!fs::is_directory(parent))throw std::runtime_error("Output directory does not exist");auto stamp=std::chrono::high_resolution_clock::now().time_since_epoch().count();auto temp=parent/(output.filename().string()+".tmp-"+std::to_string(stamp));try{{std::ofstream f(temp,std::ios::binary|std::ios::trunc);if(!f)throw std::runtime_error("Cannot create temporary output");f<<text;f.flush();if(!f)throw std::runtime_error("Could not finish writing output");}fs::create_hard_link(temp,output);std::error_code cleanup_error;fs::remove(temp,cleanup_error);}catch(const std::exception&e){std::error_code ec;fs::remove(temp,ec);throw std::runtime_error(std::string("Atomic export failed: ")+e.what());}}
struct Args {fs::path input,output,map;bool inspect=false;};
inline Args arguments(int argc,char**argv){Args a;for(int i=1;i<argc;++i){std::string k=argv[i];if(k=="--inspect"){a.inspect=true;continue;}if(i+1>=argc)throw std::runtime_error("Missing argument value");if(k=="--input")a.input=argv[++i];else if(k=="--output")a.output=argv[++i];else if(k=="--map")a.map=argv[++i];else throw std::runtime_error("Unknown option: "+k);}if(a.input.empty()||(!a.inspect&&a.output.empty()))throw std::runtime_error("Usage: migrator --input FILE [--map mapping.tsv] --output NEW.json; or --input FILE --inspect");return a;}
